# Request to send otp to a number
POST http://localhost:3000/auth/verify HTTP/1.1
content-type: application/json

{
	"phoneNo": 9173475011133
}

###
# Request to verify the opt send to a given number
POST http://localhost:3000/auth/verify/otp HTTP/1.1
Content-Type: application/json

{
	"phoneNo": 917347501113,
	"otp": "0363"
}

###
# Request to register a user given its details
POST http://localhost:3000/auth/user/signup HTTP/1.1
Content-Type: application/json

{
	"name": "Raman Preet Singh 2",
	"phoneNo": "7347501112",
	"password": "test2222",
	"age": "18",
	"gender": "Male"
}

###
# Request for signin with password
POST http://localhost:3000/auth/user/signin/password HTTP/1.1
Content-Type: application/json

{
	"phoneNo": "7347501113",
	"password": "test2222"

}

###
# Request for signin with refresh token
POST http://localhost:3000/auth/user/signin/refresh HTTP/1.1
Content-Type: application/json

{
	"refreshToken": "5d773985-ed19-423c-8128-071dceb42882"

}

###
# Testing the signin
GET http://localhost:3000/auth/secret HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZTlkYzQ5ZGM2NGJmMTU3ZDJiYTM1OCIsInBob25lTm8iOjczNDc1MDExMTMsImlhdCI6MTYyNjE3NjcwMiwiZXhwIjoxNjI2MTgwMzAyfQ.ubgbUFdSOIRZYMcIpvPBnjjIC7qWRlDbZoc9CUnhNfs


###
# Get all the user collection or collection for specific category
GET http://localhost:3000/user/collection? HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZTlkYzQ5ZGM2NGJmMTU3ZDJiYTM1OCIsInBob25lTm8iOjczNDc1MDExMTMsImlhdCI6MTYyNjE3NjcwMiwiZXhwIjoxNjI2MTgwMzAyfQ.ubgbUFdSOIRZYMcIpvPBnjjIC7qWRlDbZoc9CUnhNfs


###
#  Delete a specific collection document
DELETE http://localhost:3000/user/collection/delete/60ed7b22fe3f599a7b48a597 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZTlkYzQ5ZGM2NGJmMTU3ZDJiYTM1OCIsInBob25lTm8iOjczNDc1MDExMTMsImlhdCI6MTYyNjE3NjcwMiwiZXhwIjoxNjI2MTgwMzAyfQ.ubgbUFdSOIRZYMcIpvPBnjjIC7qWRlDbZoc9CUnhNfs


###
# Get All looks
GET http://localhost:3000/user/looks HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZTlkYzQ5ZGM2NGJmMTU3ZDJiYTM1OCIsInBob25lTm8iOjczNDc1MDExMTMsImlhdCI6MTYyNjE3NjcwMiwiZXhwIjoxNjI2MTgwMzAyfQ.ubgbUFdSOIRZYMcIpvPBnjjIC7qWRlDbZoc9CUnhNfs

###
# Create a new look
POST  http://localhost:3000/user/looks/new HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZTlkYzQ5ZGM2NGJmMTU3ZDJiYTM1OCIsInBob25lTm8iOjczNDc1MDExMTMsImlhdCI6MTYyNjE3NjcwMiwiZXhwIjoxNjI2MTgwMzAyfQ.ubgbUFdSOIRZYMcIpvPBnjjIC7qWRlDbZoc9CUnhNfs

{
	"type": "Triplet",
	"name": "Look 3",
	"clothings": [
		"60ed7b1cfe3f599a7b48a593",
		"60e9dc49dc64bf157d2ba358"
	]
}

###
#  Delete a specific collection document
DELETE http://localhost:3000/user/looks/delete/60ed7c8e0598789fcc3b00d9 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZTlkYzQ5ZGM2NGJmMTU3ZDJiYTM1OCIsInBob25lTm8iOjczNDc1MDExMTMsImlhdCI6MTYyNjE3NjcwMiwiZXhwIjoxNjI2MTgwMzAyfQ.ubgbUFdSOIRZYMcIpvPBnjjIC7qWRlDbZoc9CUnhNfs
