# Request to send otp to a number
POST http://localhost:3000/auth/verify HTTP/1.1
content-type: application/json

{
	"phoneNo": 917347501113
}

###
# Request to verify the opt send to a given number
POST http://localhost:3000/auth/verify/otp HTTP/1.1
Content-Type: application/json

{
	"phoneNo": 917347501113,
	"otp": "0363"
}

###
# Request to register a user given its details
POST http://localhost:3000/auth/user/signup HTTP/1.1
Content-Type: application/json

{
	"name": "Raman Preet Singh",
	"phoneNo": "7347501113",
	"password": "test2222",
	"age": "18",
	"gender": "Male"
}

###
# Request for signin with password
POST http://localhost:3000/auth/user/signin/password HTTP/1.1
Content-Type: application/json

{
	"phoneNo": "7347501113",
	"password": "test2233"

}

###
# Request for signin with refresh token
POST http://localhost:3000/auth/user/signin/refresh HTTP/1.1
Content-Type: application/json

{
	"refreshToken": "5921f12d-b9bb-4043-a7f7-462e76a87fb7"

}

###
# Testing the signin
GET http://localhost:3000/auth/secret HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZjY4Y2FmYjkzNTAwZDY2MDVhNjU4NCIsImlhdCI6MTYyNjgwNDg0MSwiZXhwIjoxNjI2ODA4NDQxfQ.p6jjODadSJT1PvlbivMpLg82GFBUJQfNGTdFomLEFY8

###
# Request for changing the password
POST http://localhost:3000/auth/user/change/password HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZjY4Y2FmYjkzNTAwZDY2MDVhNjU4NCIsImlhdCI6MTYyNjgwNDg0MSwiZXhwIjoxNjI2ODA4NDQxfQ.p6jjODadSJT1PvlbivMpLg82GFBUJQfNGTdFomLEFY8

{
	"oldPassword": "test2",
	"newPassword": "test23"

}

###
# Get all the user collection or collection for specific category
GET http://localhost:3000/user/collection HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZjY4Y2FmYjkzNTAwZDY2MDVhNjU4NCIsImlhdCI6MTYyNjgwNDg0MSwiZXhwIjoxNjI2ODA4NDQxfQ.p6jjODadSJT1PvlbivMpLg82GFBUJQfNGTdFomLEFY8


###
#  Delete a specific collection document
DELETE http://localhost:3000/user/collection/delete/60f6b1030e74e19d280375c6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZjY4Y2FmYjkzNTAwZDY2MDVhNjU4NCIsImlhdCI6MTYyNjgwNDg0MSwiZXhwIjoxNjI2ODA4NDQxfQ.p6jjODadSJT1PvlbivMpLg82GFBUJQfNGTdFomLEFY8


###
# Get All looks
GET http://localhost:3000/user/looks HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZjY4Y2FmYjkzNTAwZDY2MDVhNjU4NCIsImlhdCI6MTYyNjgwNDg0MSwiZXhwIjoxNjI2ODA4NDQxfQ.p6jjODadSJT1PvlbivMpLg82GFBUJQfNGTdFomLEFY8

###
# Create a new look
POST  http://localhost:3000/user/looks/new HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZjY4Y2FmYjkzNTAwZDY2MDVhNjU4NCIsImlhdCI6MTYyNjgwNDg0MSwiZXhwIjoxNjI2ODA4NDQxfQ.p6jjODadSJT1PvlbivMpLg82GFBUJQfNGTdFomLEFY8

{
	"type": "Party",
	"name": "Party 2",
	"clothings": [
		"60f6ae1f14d1d485751bfe6d",
		"60f6ae2b14d1d485751bfe71"
	]
}

###
#  Delete a specific look
DELETE http://localhost:3000/user/looks/delete/60f6b1d5dfdd26a050ede1bb HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZjY4Y2FmYjkzNTAwZDY2MDVhNjU4NCIsImlhdCI6MTYyNjgwNDg0MSwiZXhwIjoxNjI2ODA4NDQxfQ.p6jjODadSJT1PvlbivMpLg82GFBUJQfNGTdFomLEFY8


###
# Creating a new Shopping List
POST http://localhost:3000/user/shopping/list/new HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZjY4Y2FmYjkzNTAwZDY2MDVhNjU4NCIsImlhdCI6MTYyNjgwNDg0MSwiZXhwIjoxNjI2ODA4NDQxfQ.p6jjODadSJT1PvlbivMpLg82GFBUJQfNGTdFomLEFY8


{
	"title":"List 5",
	"items": [
		"Item 1",
		"Item 2",
		"Item 3"
	]
}

###
# Getting all shopping list  by user
GET http://localhost:3000/user/shopping/list/all HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZjY4Y2FmYjkzNTAwZDY2MDVhNjU4NCIsImlhdCI6MTYyNjgwNDg0MSwiZXhwIjoxNjI2ODA4NDQxfQ.p6jjODadSJT1PvlbivMpLg82GFBUJQfNGTdFomLEFY8

###
# Getting specific list
GET http://localhost:3000/user/shopping/list/60f69191626e3ef4a8b83185 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZjY4Y2FmYjkzNTAwZDY2MDVhNjU4NCIsImlhdCI6MTYyNjgwNDg0MSwiZXhwIjoxNjI2ODA4NDQxfQ.p6jjODadSJT1PvlbivMpLg82GFBUJQfNGTdFomLEFY8

###
# Deleting a  specific list
DELETE  http://localhost:3000/user/shopping/list/delete/60f69184626e3ef4a8b83181 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZjY4Y2FmYjkzNTAwZDY2MDVhNjU4NCIsImlhdCI6MTYyNjgwNDg0MSwiZXhwIjoxNjI2ODA4NDQxfQ.p6jjODadSJT1PvlbivMpLg82GFBUJQfNGTdFomLEFY8


###
# Editing a existing Shopping List
POST http://localhost:3000/user/shopping/list/update/60f69191626e3ef4a8b83185 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZjY4Y2FmYjkzNTAwZDY2MDVhNjU4NCIsImlhdCI6MTYyNjgwNDg0MSwiZXhwIjoxNjI2ODA4NDQxfQ.p6jjODadSJT1PvlbivMpLg82GFBUJQfNGTdFomLEFY8


{
	"title":"List 2",
	"items": [
	]
}